# https://immich.app/docs/install/environment-variables


x-common-environment: &common_environment
  TZ: 'Australia/Sydney'
  PUID: 1000
  PGID: 1000
  UPLOAD_LOCATION: /mnt/nobackup/immich_upload
  IMMICH_VERSION: release
  TYPESENSE_API_KEY: CHANGE_ME
  DB_HOSTNAME: immich_database
  DB_DATABASE_NAME: immich
  DB_USERNAME: postgres
  DB_PASSWORD: CHANGE_ME
  POSTGRES_DB: immich
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: CHANGE_ME
  REDIS_HOSTNAME: immich_cache

services:
  # ---------------------------------------------------------------------
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/nobackup/immich_upload:/usr/src/app/upload
      - /mnt/images:/mnt/images
    environment:
      <<: *common_environment
    ports:
      - 2283:3001
    depends_on:
      - immich_cache
      - immich_database
    restart: unless-stopped
  # ---------------------------------------------------------------------
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hardware_accelleration.yaml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - /mnt/nobackup/immich_upload:/usr/src/app/upload
      - /mnt/images:/mnt/images
    environment:
      <<: *common_environment
    depends_on:
      - immich_cache
      - immich_database
    restart: unless-stopped
  # ---------------------------------------------------------------------
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /home/photosadmin/model-cache:/cache
    environment:
      <<: *common_environment
    restart: unless-stopped
  # ---------------------------------------------------------------------
  immich_cache:
    container_name: immich_cache
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: unless-stopped
  # ---------------------------------------------------------------------
  immich_database:
    container_name: immich_database
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      <<: *common_environment
    volumes:
      - /home/photosadmin/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
